import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../Components/nav/Nav";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Enoch Fabiyi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="parentContainer">
        <section className={styles.HeadSection}>
          <Nav />
        </section>
      </div>
    </div>
  );
}
