import Head from "next/head";
import styles from "../styles/Home.module.css";
import HeadSection from "../Components/HeadSection/HeadSection";
import Projects from "../Components/Projects/Projects";
import About from "../Components/About/About";
import ContactMe from "../Components/ContactMe/ContactMe";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Enoch Fabiyi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="parentContainer">
        <HeadSection />
        <Projects />
        <About />
        <ContactMe />
      </div>
    </div>
  );
}
